-- Enable RLS
alter table if exists public.ticket_statuses enable row level security;
alter table if exists public.ticket_modules enable row level security;
alter table if exists public.ticket_slas enable row level security;

-- Create Tables if they don't exist
create table if not exists public.ticket_statuses (
  id bigint generated by default as identity primary key,
  label text not null,
  color_hex text not null,
  sort_order int not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.ticket_modules (
  id bigint generated by default as identity primary key,
  label text not null,
  sort_order int not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.ticket_slas (
  id bigint generated by default as identity primary key,
  priority text not null unique, -- 'Critical', 'High', 'Medium', 'Low'
  resolution_hours int not null default 24,
  color_hex text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies

-- Statuses: Everyone can read, only authenticated can modify (or restrict to admins if needed)
create policy "Enable read access for all users" on public.ticket_statuses for select using (true);
create policy "Enable insert for authenticated users only" on public.ticket_statuses for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.ticket_statuses for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.ticket_statuses for delete using (auth.role() = 'authenticated');

-- Modules: Everyone can read, only authenticated can modify
create policy "Enable read access for all users" on public.ticket_modules for select using (true);
create policy "Enable insert for authenticated users only" on public.ticket_modules for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.ticket_modules for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.ticket_modules for delete using (auth.role() = 'authenticated');

-- SLAs: Everyone can read, only authenticated can modify
create policy "Enable read access for all users" on public.ticket_slas for select using (true);
create policy "Enable insert for authenticated users only" on public.ticket_slas for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.ticket_slas for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.ticket_slas for delete using (auth.role() = 'authenticated');

-- Seed Initial Data (Optional - use ON CONFLICT to avoid errors)
insert into public.ticket_statuses (label, color_hex, sort_order) values
  ('Open', '#3b82f6', 10),
  ('To be Investigated', '#a855f7', 20),
  ('Open Bug', '#ef4444', 30),
  ('In Progress', '#eab308', 40),
  ('Pending User Info', '#f97316', 50),
  ('User Acceptance', '#06b6d4', 60),
  ('Resolved', '#22c55e', 70),
  ('Partially Closed', '#64748b', 80),
  ('Closed', '#1e293b', 90),
  ('Reopened', '#f43f5e', 100)
on conflict do nothing;

insert into public.ticket_modules (label, sort_order) values
  ('Finance', 10),
  ('Sales', 20),
  ('Inventory', 30),
  ('Manufacturing', 40),
  ('HR', 50),
  ('System', 60)
on conflict do nothing;

insert into public.ticket_slas (priority, resolution_hours, color_hex) values
  ('Critical', 4, '#ef4444'),
  ('High', 8, '#f97316'),
  ('Medium', 24, '#3b82f6'),
  ('Low', 48, '#22c55e')
on conflict (priority) do nothing;
