-- Create ticket_slas table
CREATE TABLE IF NOT EXISTS ticket_slas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority TEXT NOT NULL UNIQUE,
    resolution_hours NUMERIC NOT NULL,
    color_hex TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE ticket_slas ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for all authenticated users
CREATE POLICY "Enable read access for all users" ON ticket_slas
    FOR SELECT USING (true);

-- Create policy to allow insert/update/delete for authenticated users (for now, ideally restricted to admins)
CREATE POLICY "Enable write access for all users" ON ticket_slas
    FOR ALL USING (true);

-- Insert default values
INSERT INTO ticket_slas (priority, resolution_hours, color_hex)
VALUES
    ('Critical', 4, '#ef4444'),
    ('High', 8, '#f97316'),
    ('Medium', 24, '#3b82f6'),
    ('Low', 48, '#64748b')
ON CONFLICT (priority) DO NOTHING;
